/*
 * Regenerates src/internal/merge-engine/tables.generated.ts (the default
 * tables shipped in the package) from the vendored default config.
 *
 *   pnpm compile-tables
 *
 * The compiler and the default config are TypeScript sources, so they are
 * bundled on the fly with esbuild (no build step required). A test compares
 * the checked-in file against a fresh compile, so CI catches a stale file.
 */
import {build} from "esbuild";

import {execFileSync} from "node:child_process";
import {mkdtempSync, rmSync, writeFileSync} from "node:fs";
import {createRequire} from "node:module";
import os from "node:os";
import path from "node:path";
import {pathToFileURL} from "node:url";

const require = createRequire(import.meta.url);
const repoRoot = path.resolve(import.meta.dirname, "..");
const outputPath = path.join(repoRoot, "src", "internal", "merge-engine", "tables.generated.ts");
const biomeCli = require.resolve("@biomejs/biome/bin/biome");

export const BANNER =
  "// GENERATED by scripts/compile-tables.mjs from the vendored default config. Do not edit.";

const loadCompiler = async () => {
  const tempDir = mkdtempSync(path.join(os.tmpdir(), "tv-compile-tables-"));
  const bundlePath = path.join(tempDir, "compiler.mjs");

  try {
    await build({
      stdin: {
        contents: `
          export {compileStats, compileToSource} from "./src/internal/merge-engine/compiler.ts";
          export {getDefaultConfig} from "./src/internal/compile-config/default-config.ts";
        `,
        resolveDir: repoRoot,
        loader: "ts",
      },
      bundle: true,
      format: "esm",
      platform: "node",
      target: "node18",
      outfile: bundlePath,
      logLevel: "silent",
    });

    return await import(pathToFileURL(bundlePath).href);
  } finally {
    rmSync(tempDir, {force: true, recursive: true});
  }
};

export const generateTablesSource = async () => {
  const {compileStats, compileToSource, getDefaultConfig} = await loadCompiler();
  const source = compileToSource(getDefaultConfig(), {lang: "ts", banner: BANNER});

  return {source, stats: compileStats(getDefaultConfig())};
};

const {source, stats} = await generateTablesSource();

writeFileSync(outputPath, source);
execFileSync(process.execPath, [biomeCli, "format", "--write", outputPath], {
  cwd: repoRoot,
  stdio: "inherit",
});

console.log(
  `compiled: ${stats.groups} groups, ${stats.nodes} nodes, ${stats.edges} edges, ` +
    `${stats.liftedLiterals} lifted literals (${stats.uniqueTails} tails), ` +
    `${(source.length / 1024).toFixed(1)} KB source → ${path.relative(repoRoot, outputPath)}`,
);
